# Generated by Django 4.1.3 on 2022-11-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_exercise_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('picture', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='unitType',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='picture',
            field=models.CharField(max_length=50),
        ),
    ]
