# Generated by Django 4.1.3 on 2022-11-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_unitamount1_clientexercise_unitamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientexercise',
            name='unitAmount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='picture',
            field=models.CharField(max_length=200),
        ),
    ]
