# Generated by Django 4.1.3 on 2022-11-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_clientexercise_date'),
        ('main_app', '0004_delete_client_remove_exercise_unittype_and_more'),
    ]

    operations = [
    ]
